remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

locale: "en"
include: ["_pages"]
title: ""
logo: "/images/GGG-logo.png"

url: https://globalgrassygroup.github.io/

footer:
  title: "Global Grassy Group"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GlobalGrassyGroup"

atom_feed:
  hide: true
